name: 'GitHub Content Management System'
description: 'Content is stored as GitHub Issues, managed through GitHub Projects, published by GitHub Actions and hosted by GitHub Pages.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'edit-3'
  color: 'orange'
